theme: jekyll-theme-minimal
title: Juan Pan - Trista
description: SphereEx Co-Founder, Apache Member, Apache ShardingSphere PMC & Apache brpc (Incubator) Mentor & Apache age (Incubator) Mentor.~~<br/><br/> She used to be responsible for the design and development of the intelligent database platform of JD Digital Science and Technology. She now focuses on the distributed database & middleware ecosystem, and open-source community. Recipient of the “2020 China Open-Source Pioneer” award & the “2021 OSCAR 2021 Top Open Source Pioneer”.
show_downloads: false
logo: images/avatar.png
