theme: jekyll-theme-minimal
title: Juan Pan (Trista)
description: Hi there, This is Trista, nice to meet you! <br/><br/> 初めまして、潘娟と申します。よろしくお願いしますね。^_^ <br/><br/>SphereEx co-founder & Apache memeber & Apache ShardingSphere PMC & Apache brpc(Incubator) mentor，前京东科技高级DBA，曾负责京东数科数据库智能平台的设计与研发，现专注于分布式数据库 & 中间件生态及开源领域。被评为《2020中国开源先锋人物》，多次受邀参加数据库 & 架构领域的相关会议分享。
show_downloads: false
logo: images/avatar.png
