theme: jekyll-theme-minimal
title: Juan Pan (Trista)
description: Hi everyone, This is Trista, nice to meet you. ^_^ 初めまして、ぱんと申します。よろしくお願いしますね。
show_downloads: false
logo: https://github.com/tristaZero/tristaZero.github.io/blob/master/images/avatar.jpg