theme: jekyll-theme-minimal
title: Juan Pan (Trista)
description: Hi everyone, This is Trista, nice to meet you. :-)
show_downloads: false
logo: https://github.com/tristaZero/tristaZero.github.io/blob/master/images/avatar.jpg